package com.jack.compsci;

import java.text.NumberFormat;
import java.util.Locale;

public class SalePredictionJC {



    public static void main(String[] args) {
        double totalRevenue = 3600000;
        double percentageGenerated = calculatePercentage(totalRevenue, 0.48f);
        System.out.println("(More Accurate) Blue Whale's sales divison has generated " + currencyFormat(percentageGenerated));

        System.out.println("(Basic) Blue Whale's sales divison has generated $" + (int)totalRevenue * 0.48);

    }


    /**
     * Not entirely necessary, but because I'm using doubles I want them to look nice when we print.
     * @param numbers -  currency amount we're trying to format
     * @return - returns a formatted US currency value.
     */
    private static String currencyFormat(double numbers) {
        NumberFormat numberFormat = NumberFormat.getCurrencyInstance(Locale.US);
        return numberFormat.format(numbers);
    }
    /**
     * I'm not sure if you're okay with me using seperate method for this, so I'll do it both ways.
     * @param revenue - Represents the companies yearly revenue generated
     * @param percentage - Percentage of revenue generated
     * @return - Returns the amount of money generated by a specific company.
     */
    private static double calculatePercentage(double revenue, float percentage) {
        return revenue * percentage;
    }
}
